sudo: required
services: 
  - docker

before_install:
  - docker build -t jawade/docker-udemy-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jawade/docker-udemy-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-udemy-react"
  env: "DockerUdemyReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-471491298032"
  bucket_path: "docker-udemy-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"