sudo: required
services: 
  - docker

  before_install:
    - docker build -t jawade/docker-udemy-react -f Dockerfile.dev .

  script:
    - docker run jawade/docker-udemy-react npm run test -- --coverage